name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCC
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Build project
      run: make

    - name: Run tests
      run: make test
